apiVersion: v1
kind: Service
metadata:
  name: employee-app
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080