apiVersion: v1
kind: ServiceAccount
metadata:
  name: astra-dashboard-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astra-dashboard-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: astra-dashboard-binding
subjects:
- kind: ServiceAccount
  name: astra-dashboard-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: astra-dashboard-role
  apiGroup: rbac.authorization.k8s.io
