---
apiVersion: v1
kind: Service
metadata:
  name: employee-app-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080  # Accessible at http://<EC2-IP>:30080
  selector:
    app: employee-app

---
apiVersion: v1
kind: Service
metadata:
  name: astra-xdr-dashboard-service
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081  # Accessible at http://<EC2-IP>:30081
  selector:
    app: astra-xdr-dashboard
